import { CardNumber, CardType, Suit } from "../../components";

/**
 *
 */
export default (): CardType[] => [
  // Spades
  { suit: Suit.SPADES, card: CardNumber.ACE },
  { suit: Suit.SPADES, card: CardNumber.TWO },
  { suit: Suit.SPADES, card: CardNumber.THREE },
  { suit: Suit.SPADES, card: CardNumber.FOUR },
  { suit: Suit.SPADES, card: CardNumber.FIVE },
  { suit: Suit.SPADES, card: CardNumber.SIX },
  { suit: Suit.SPADES, card: CardNumber.SEVEN },
  { suit: Suit.SPADES, card: CardNumber.EIGHT },
  { suit: Suit.SPADES, card: CardNumber.NINE },
  { suit: Suit.SPADES, card: CardNumber.TEN },
  { suit: Suit.SPADES, card: CardNumber.JACK },
  { suit: Suit.SPADES, card: CardNumber.QUEEN },
  { suit: Suit.SPADES, card: CardNumber.KING },
  // Diamonds
  { suit: Suit.DIAMONDS, card: CardNumber.ACE },
  { suit: Suit.DIAMONDS, card: CardNumber.TWO },
  { suit: Suit.DIAMONDS, card: CardNumber.THREE },
  { suit: Suit.DIAMONDS, card: CardNumber.FOUR },
  { suit: Suit.DIAMONDS, card: CardNumber.FIVE },
  { suit: Suit.DIAMONDS, card: CardNumber.SIX },
  { suit: Suit.DIAMONDS, card: CardNumber.SEVEN },
  { suit: Suit.DIAMONDS, card: CardNumber.EIGHT },
  { suit: Suit.DIAMONDS, card: CardNumber.NINE },
  { suit: Suit.DIAMONDS, card: CardNumber.TEN },
  { suit: Suit.DIAMONDS, card: CardNumber.JACK },
  { suit: Suit.DIAMONDS, card: CardNumber.QUEEN },
  { suit: Suit.DIAMONDS, card: CardNumber.KING },
  // Clubs
  { suit: Suit.CLUBS, card: CardNumber.ACE },
  { suit: Suit.CLUBS, card: CardNumber.TWO },
  { suit: Suit.CLUBS, card: CardNumber.THREE },
  { suit: Suit.CLUBS, card: CardNumber.FOUR },
  { suit: Suit.CLUBS, card: CardNumber.FIVE },
  { suit: Suit.CLUBS, card: CardNumber.SIX },
  { suit: Suit.CLUBS, card: CardNumber.SEVEN },
  { suit: Suit.CLUBS, card: CardNumber.EIGHT },
  { suit: Suit.CLUBS, card: CardNumber.NINE },
  { suit: Suit.CLUBS, card: CardNumber.TEN },
  { suit: Suit.CLUBS, card: CardNumber.JACK },
  { suit: Suit.CLUBS, card: CardNumber.QUEEN },
  { suit: Suit.CLUBS, card: CardNumber.KING },
  // Hearts
  { suit: Suit.HEARTS, card: CardNumber.ACE },
  { suit: Suit.HEARTS, card: CardNumber.TWO },
  { suit: Suit.HEARTS, card: CardNumber.THREE },
  { suit: Suit.HEARTS, card: CardNumber.FOUR },
  { suit: Suit.HEARTS, card: CardNumber.FIVE },
  { suit: Suit.HEARTS, card: CardNumber.SIX },
  { suit: Suit.HEARTS, card: CardNumber.SEVEN },
  { suit: Suit.HEARTS, card: CardNumber.EIGHT },
  { suit: Suit.HEARTS, card: CardNumber.NINE },
  { suit: Suit.HEARTS, card: CardNumber.TEN },
  { suit: Suit.HEARTS, card: CardNumber.JACK },
  { suit: Suit.HEARTS, card: CardNumber.QUEEN },
  { suit: Suit.HEARTS, card: CardNumber.KING },
];
